Rails:
  Enabled: true

AllCops:
  Exclude:
    - '.bundle/**/*'
    - 'bin/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.1

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Documentation:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/TrivialAccessors:
  AllowDSLWriters: true

Style/PredicateName:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false
