# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf1d1b88fdd7d8e05da5077e2790d2d294cec9b4759e615219202895d49fb89b4f2ce157549a40458245a2fe8a8d2170acfa02503fe7841bcbae6aa9516ca8a6

test:
  secret_key_base: 05c4f652fe438ca3f5fcd079aeccea21ef299d376e82342095ec8de48fade81d984870c02940816c1fc87a2718a20803fdc0edcc258131499bb47c9780646dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
